export { default as Home } from './user/Home';
export { default as Login } from './user/Login';
export { default as Register } from './user/Register';
export { default as ProductDetail } from './user/ProductDetail';
export { default as Search } from './user/Search';
export { default as Cart } from './user/Cart';
export { default as MyOrder } from './user/Order';
export { default as Notification } from './user/Notification';

export { default as Product } from './admin/Product';
export { default as Category } from './admin/Category';
export { default as Brand } from './admin/Brand';
export { default as Banner } from './admin/Banner';
export { default as Order } from './admin/Order';
export { default as Account } from './admin/Account';
export { default as Dashboard } from './admin/Dashboard';
export { default as Feedback } from './admin/Feedback';
export { default as News } from './admin/News';
export { default as NotFound } from './admin/NotFound';
